services:
  - type: web
    name: n8n-groceryfresh
    env: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: 7777ramlu
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 7777ramlu7777@@
      - key: N8N_HOST
        value: n8n-groceryfresh.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n-groceryfresh.onrender.com
